### ISSUE TITLE
Check if Google Play Protect is disabled

### ISSUE THREAD

**Issue by Te-k** [spytrap-org/spytrap-adb#18]
That's a very suspicious sign of a potential stalkerware (or spyware).

This information is available in settings (not sure if it is global or secure) and the values are `package_verifier_enable`,  `package_verifier_user_consent` and `upload_apk_enable`.

See the [code in MVT](https://github.com/mvt-project/mvt/blob/main/mvt/android/modules/adb/settings.py)

**Comment by kpcyrd** [comment]
Added, thanks! If you have suggestions regarding the user messages let me know. :)
